### ISSUE TITLE
All responses on all paths behave like `urdad` after `urdad` was called at least once

### ISSUE THREAD

**Issue by vilunov** [dmtrKovalenko/macos-assembly-http-server#1]
Reproduction steps:
- Launch the server
- Call `curl -v localhost:6969`, observe the 413 mama response.
- Call `curl -v localhost:6969/urdad`, observe the 410 milk response.
- Call `curl -v localhost:6969` again and observer the 410 milk response.

This is fixed after a restart.

Expected behaviour:
Non-urdad paths will never return the milk response.

Pls fix, unfortunately I have to use my node.js server for my `urfamily` service until this is fixed

**Comment by dmtrKovalenko** [comment]
Oh yeah that is caused by premature optimization lol

**Comment by dmtrKovalenko** [comment]
The issue is resolved!

**Comment by vilunov** [comment]
Thanks a lot, it works now!
